server:
  servlet:
    context-path: /tirage

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      leak-detection-threshold: 60000
      max-lifetime: 60000
    password: 288eb693bbb620f4059f9f75ab5b762366c2711777674ca04e39f37a3f53c715
    url: jdbc:postgresql://ec2-99-80-170-190.eu-west-1.compute.amazonaws.com:5432/dbu4tmhk93f69?user=fnuylavddgfdzq&password=288eb693bbb620f4059f9f75ab5b762366c2711777674ca04e39f37a3f53c715
    #url: jdbc:postgresql://fnuylavddgfdzq:288eb693bbb620f4059f9f75ab5b762366c2711777674ca04e39f37a3f53c715@ec2-99-80-170-190.eu-west-1.compute.amazonaws.com:5432/dbu4tmhk93f69
    username: fnuylavddgfdzq
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #default_schema: dbu4tmhk93f69
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    show-sql: true

logging:
  level:
    org:
      springframework: INFO

management:
  health:
    livenessState:
      enabled: true
    probes:
      enabled: true
    readinessState:
      enabled: true
