# Default values for tirageCharts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tirageapi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

resources: {}
   limits:
     cpu: 600m
     memory: 600Mi
   requests:
     cpu: 500m
     memory: 500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
